# Generated by Django 5.2.12 on 2026-03-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_path', models.CharField(blank=True, default='', max_length=255)),
                ('biography', models.TextField(blank=True, default='')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=255)),
                ('known_for_department', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('original_title', models.CharField(blank=True, default='', max_length=500)),
                ('overview', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0)),
                ('poster_path', models.CharField(blank=True, default='', max_length=255)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=255)),
                ('budget', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('homepage', models.URLField(blank=True, default='', max_length=500)),
                ('trailer_key', models.CharField(blank=True, default='', help_text='YouTube video key for the trailer', max_length=50)),
                ('wikipedia_url', models.URLField(blank=True, default='', max_length=500)),
                ('wikipedia_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('movie', 'person', 'character')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_movies', through='movies.MovieCast', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_movies', to='movies.person'),
        ),
        migrations.CreateModel(
            name='WatchProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('stream', 'Streaming'), ('rent', 'Rent'), ('buy', 'Buy'), ('free', 'Free')], max_length=10)),
                ('logo_path', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('country_code', models.CharField(default='US', max_length=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_providers', to='movies.movie')),
            ],
            options={
                'ordering': ['provider_type', 'provider_name'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-vote_average', '-vote_count'], name='movies_movi_vote_av_b76c43_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-popularity'], name='movies_movi_popular_3c541f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
    ]
