# Generated by Django 5.2.12 on 2026-03-11 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_tmdb_id', models.IntegerField()),
                ('genre_name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0, help_text='Computed preference score 0-100')),
                ('interaction_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('user', 'genre_tmdb_id')},
            },
        ),
        migrations.CreateModel(
            name='UserMovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_tmdb_id', models.IntegerField(db_index=True)),
                ('movie_title', models.CharField(blank=True, default='', max_length=500)),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('like', 'Liked'), ('dislike', 'Disliked'), ('watchlist', 'Added to Watchlist'), ('watched', 'Watched'), ('search', 'Searched')], max_length=20)),
                ('genre_ids', models.JSONField(blank=True, default=list, help_text='Genre IDs at time of interaction')),
                ('rating', models.FloatField(blank=True, help_text='User rating 1-10', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_dd110e_idx'), models.Index(fields=['user', 'interaction_type'], name='recommendat_user_id_d8f6b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_tmdb_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=500)),
                ('poster_path', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'movie_tmdb_id')},
            },
        ),
    ]
